@minimalApi_HostAddress = http://localhost:5292
@gamesRoute = api/v1/games

GET {{minimalApi_HostAddress}}/

###
GET {{minimalApi_HostAddress}}/{{gamesRoute}}

###
GET {{minimalApi_HostAddress}}/{{gamesRoute}}/3

###
POST {{minimalApi_HostAddress}}/{{gamesRoute}}
Content-Type: application/json

{
    "name": "GTA 6",
    "genreId": 2,
    "price": 33.9,
    "releaseDate": "2022-02-11"
}

###
PUT {{minimalApi_HostAddress}}/{{gamesRoute}}/1
Content-Type: application/json

{
    "name": "Need for Speed",
    "genreId": 4,
    "price": 87.9,
    "releaseDate": "2016-06-23"
}

###
DELETE {{minimalApi_HostAddress}}/{{gamesRoute}}/2