@minimalApi_HostAddress = http://localhost:5292
@gamesRoute = api/v1/games
@id=4


GET {{minimalApi_HostAddress}}/

###

GET {{minimalApi_HostAddress}}/api/v1/games

###

POST {{minimalApi_HostAddress}}/api/v1/games
Content-Type: application/json

{
    "name": "FortNite",
    "genreId": 4,
    "price": 33.9,
    "releaseDate": "2022-02-11"
}

###

DELETE {{minimalApi_HostAddress}}/api/v1/games/{{id}}

###

GET {{minimalApi_HostAddress}}/api/v1/games/{{id}}

###

PUT {{minimalApi_HostAddress}}/api/v1/games/{{id}}
Content-Type: application/json

{
    "name": "FortNite",
    "genreId": 2,
    "price": 33.9,
    "releaseDate": "2018-10-29"
}

###

GET {{minimalApi_HostAddress}}/api/v1/genres

###
