@minimalApi_HostAddress = http://localhost:5292

GET {{minimalApi_HostAddress}}/

###
GET {{minimalApi_HostAddress}}/api/v1/games

###
GET {{minimalApi_HostAddress}}/api/v1/games/6

###
POST {{minimalApi_HostAddress}}/api/v1/games
Content-Type: application/json

{
    "name": "Minecraftfffffffffffffffffffffffffffff",
    "genre": "Building",
    "price": 34.4,
    "releaseDate": "2015-07-13"
}

###
PUT {{minimalApi_HostAddress}}/api/v1/games/5
Content-Type: application/json

{
    "name": "Another",
    "genre": "Building",
    "price": 22.5,
    "releaseDate": "1997-07-26"
}